### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by chinesedfan** [chinesedfan/yarn-merge#1]
- upload yarn.lock
    - [ ] draw force graph
    - [ ] list mergeable packages
    - [ ] download cleaned yarn.lock
- click any node, if in different modes,
    - [ ] show ones that have the same package name
    - [ ] path to the root
    - [ ] sub-dependencies
    - [ ] different color for different kinds of dependencies

**Comment by chinesedfan** [comment]
TODO:
- [ ] zoom and move
- [ ] show arrow
